### ISSUE TITLE
radar chart y min not working?

### ISSUE THREAD

**Issue by AlwaysABattler** [Kyvis-Labs/ignition-apexcharts-module#24] opened 2022-09-07 08:49 UTC
Hi Travis,

This is regards to the radar chart.

If I change the yaxis.min from 0 to something else, it does something strange to the chart. For example, I have the yaxis.min = 0 in the the attached file called "radar chart yaxis.min 0". It works as I expect it too. However, if I change the the yaxis.min = 50 the chart expands the series, not clipping them as I expected. The tool tip shows the value hasn't changed, but it is plotted higher on the yaxis. This can be seen in the attached file "radar chart yaxis min 50". 

many thanks if you can look into this.
<img width="688" alt="radar chart yaxis min 0" src="https://user-images.githubusercontent.com/92848133/188834122-516e92c6-f3e8-4478-898b-b3b0c4c46d7e.png">
<img width="698" alt="radar chart yaxis min 50" src="https://user-images.githubusercontent.com/92848133/188834133-b6633523-b05c-431a-82c1-50d72cc754d0.png">

**Comment by traviscox** [comment] 2022-09-09 17:59
Any chance you can export the view so I can troubleshoot?

**Comment by AlwaysABattler** [comment] 2022-09-12 02:29
Hi Travis,

Please see attached for troubleshooting.

[gas turbine.zip](https://github.com/Kyvis-Labs/ignition-apexcharts-module/files/9544179/gas.turbine.zip)

**Comment by MrDougLawrie** [comment] 2022-09-30 04:35
I am also keen to see a fix for this.

**Comment by traviscox** [comment] 2023-01-28 19:46
I was able to replicate that issue outside of Ignition. So, the issue is with Apex Charts itself. I don't think you are meant to change the min and max for the radar chart. I simply removed both settings and everything worked properly. You would have to post this question to the Apex Charts forums.

**Closed by traviscox** 2023-01-28 19:46 UTC
